"use strict";

/*
  data.js
  Quiz data is grouped by series first, then by idol number.
  Image paths are relative to assets/idols/.
  Compatibility exports at the bottom keep script.js stable.
*/
(() => {
  const ALLSTARS_IDOLS = [
    { no: 1, series: "allstars", attribute: "Princess", group: "765PRO ALLSTARS", jpName: "天海 春香", name: "아마미 하루카", hex: "#e22b30", image: "allstars/Haruka_Amami.webp" },
    { no: 2, series: "allstars", attribute: "Fairy", group: "765PRO ALLSTARS", jpName: "如月 千早", name: "키사라기 치하야", hex: "#2743d2", image: "allstars/Chihaya_Kisaragi.webp" },
    { no: 3, series: "allstars", attribute: "Angel", group: "765PRO ALLSTARS", jpName: "星井 美希", name: "호시이 미키", hex: "#b4e04b", image: "allstars/Miki_Hoshii.webp" },
    { no: 4, series: "allstars", attribute: "Princess", group: "765PRO ALLSTARS", jpName: "萩原 雪歩", name: "하기와라 유키호", hex: "#d3dde9", image: "allstars/Yukiho_Hagiwara.webp" },
    { no: 5, series: "allstars", attribute: "Angel", group: "765PRO ALLSTARS", jpName: "高槻 やよい", name: "타카츠키 야요이", hex: "#f39939", image: "allstars/Yayoi_Takatsuki.webp" },
    { no: 6, series: "allstars", attribute: "Princess", group: "765PRO ALLSTARS", jpName: "菊地 真", name: "키쿠치 마코토", hex: "#515558", image: "allstars/Makoto_Kikuchi.webp" },
    { no: 7, series: "allstars", attribute: "Fairy", group: "765PRO ALLSTARS", jpName: "水瀬 伊織", name: "미나세 이오리", hex: "#fd99e1", image: "allstars/Iori_Minase.webp" },
    { no: 8, series: "allstars", attribute: "Fairy", group: "765PRO ALLSTARS", jpName: "四条 貴音", name: "시죠 타카네", hex: "#a6126a", image: "allstars/Takane_Shijou.webp" },
    { no: 9, series: "allstars", attribute: "Fairy", group: "765PRO ALLSTARS", jpName: "秋月 律子", name: "아키즈키 리츠코", hex: "#01a860", image: "allstars/Ritsuko_Akizuki.webp" },
    { no: 10, series: "allstars", attribute: "Angel", group: "765PRO ALLSTARS", jpName: "三浦 あずさ", name: "미우라 아즈사", hex: "#9238be", image: "allstars/Azusa_Miura.webp" },
    { no: 11, series: "allstars", attribute: "Angel", group: "765PRO ALLSTARS", jpName: "双海 亜美", name: "후타미 아미", hex: "#ffe43f", image: "allstars/Ami_Futami.webp" },
    { no: 12, series: "allstars", attribute: "Angel", group: "765PRO ALLSTARS", jpName: "双海 真美", name: "후타미 마미", hex: "#ffe43f", image: "allstars/Mami_Futami.webp" },
    { no: 13, series: "allstars", attribute: "Princess", group: "765PRO ALLSTARS", jpName: "我那覇 響", name: "가나하 히비키", hex: "#01adb9", image: "allstars/Hibiki_Ganaha.webp" }
  ];

  const MILLION_IDOLS = [
    { no: 14, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "春日 未来", name: "카스가 미라이", hex: "#ea5b76", image: "million/Mirai_Kasuga.webp" },
    { no: 15, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "最上 静香", name: "모가미 시즈카", hex: "#6495cf", image: "million/Shizuka_Mogami.webp" },
    { no: 16, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "伊吹 翼", name: "이부키 츠바사", hex: "#fed552", image: "million/Tsubasa_Ibuki.webp" },
    { no: 17, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "田中 琴葉", name: "타나카 코토하", hex: "#92cfbb", image: "million/Kotoha_Tanaka.webp" },
    { no: 18, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "島原 エレナ", name: "시마바라 엘레나", hex: "#9bce92", image: "million/Elena_Shimabara.webp" },
    { no: 19, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "佐竹 美奈子", name: "사타케 미나코", hex: "#58a6dc", image: "million/Minako_Satake.webp" },
    { no: 20, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "所 恵美", name: "토코로 메구미", hex: "#454341", image: "million/Megumi_Tokoro.webp" },
    { no: 21, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "徳川 まつり", name: "토쿠가와 마츠리", hex: "#5abfb7", image: "million/Matsuri_Tokugawa.webp" },
    { no: 22, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "箱崎 星梨花", name: "하코자키 세리카", hex: "#ed90ba", image: "million/Serika_Hakozaki.webp" },
    { no: 23, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "野々原 茜", name: "노노하라 아카네", hex: "#eb613f", image: "million/Akane_Nonohara.webp" },
    { no: 24, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "望月 杏奈", name: "모치즈키 안나", hex: "#7e6ca8", image: "million/Anna_Mochizuki.webp" },
    { no: 25, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "ロコ", name: "로코", hex: "#fff03c", image: "million/Roco.webp" },
    { no: 26, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "七尾 百合子", name: "나나오 유리코", hex: "#c7b83c", image: "million/Yuriko_Nanao.webp" },
    { no: 27, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "高山 紗代子", name: "타카야마 사요코", hex: "#7f6575", image: "million/Sayoko_Takayama.webp" },
    { no: 28, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "松田 亜利沙", name: "마츠다 아리사", hex: "#b54461", image: "million/Arisa_Matsuda.webp" },
    { no: 29, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "高坂 海美", name: "코사카 우미", hex: "#e9739b", image: "million/Umi_Kousaka.webp" },
    { no: 30, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "中谷 育", name: "나카타니 이쿠", hex: "#f7e78e", image: "million/Iku_Nakatani.webp" },
    { no: 31, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "天空橋 朋花", name: "텐쿠바시 토모카", hex: "#bee3e3", image: "million/Tomoka_Tenkubashi.webp" },
    { no: 32, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "エミリー スチュアート", name: "에밀리 스튜어트", hex: "#554171", image: "million/Emily_Stewart.webp" },
    { no: 33, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "北沢 志保", name: "키타자와 시호", hex: "#afa690", image: "million/Shiho_Kitazawa.webp" },
    { no: 34, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "舞浜 歩", name: "마이하마 아유무", hex: "#e25a9b", image: "million/Ayumu_Maihama.webp" },
    { no: 35, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "木下 ひなた", name: "키노시타 히나타", hex: "#d1342c", image: "million/Hinata_Kinoshita.webp" },
    { no: 36, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "矢吹 可奈", name: "야부키 카나", hex: "#f5ad3b", image: "million/Kana_Yabuki.webp" },
    { no: 37, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "横山 奈緒", name: "요코야마 나오", hex: "#788bc5", image: "million/Nao_Yokoyama.webp" },
    { no: 38, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "二階堂 千鶴", name: "니카이도 치즈루", hex: "#f19557", image: "million/Chizuru_Nikaido.webp" },
    { no: 39, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "馬場 このみ", name: "바바 코노미", hex: "#f1becb", image: "million/Konomi_Baba.webp" },
    { no: 40, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "大神 環", name: "오오가미 타마키", hex: "#ee762e", image: "million/Tamaki_Ogami.webp" },
    { no: 41, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "豊川 風花", name: "토요카와 후카", hex: "#7278a8", image: "million/Fuka_Toyokawa.webp" },
    { no: 42, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "宮尾 美也", name: "미야오 미야", hex: "#d7a96b", image: "million/Miya_Miake.webp" },
    { no: 43, series: "million", attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "福田 のり子", name: "후쿠다 노리코", hex: "#eceb70", image: "million/Noriko_Fukuda.webp" },
    { no: 44, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "真壁 瑞希", name: "마카베 미즈키", hex: "#99b7dc", image: "million/Mizuki_Makabe.webp" },
    { no: 45, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "篠宮 可憐", name: "시노미야 카렌", hex: "#b63b40", image: "million/Karen_Shinomiya.webp" },
    { no: 46, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "百瀬 莉緒", name: "모모세 리오", hex: "#f19591", image: "million/Rio_Momose.webp" },
    { no: 47, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "永吉 昴", name: "나가요시 스바루", hex: "#aeb49c", image: "million/Subaru_Nagayoshi.webp" },
    { no: 48, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "北上 麗花", name: "키타카미 레이카", hex: "#6bb6b0", image: "million/Reika_Kitakami.webp" },
    { no: 49, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "周防 桃子", name: "스오 모모코", hex: "#efb864", image: "million/Momoko_Suou.webp" },
    { no: 50, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "ジュリア", name: "줄리아", hex: "#d7385f", image: "million/Julia.webp" },
    { no: 51, series: "million", attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "白石 紬", name: "시라이시 츠무기", hex: "#ebe1ff", image: "million/Tsumugi_Shirokane.webp" },
    { no: 52, series: "million", attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "桜守 歌織", name: "사쿠라모리 카오리", hex: "#274079", image: "million/Kaori_Sakuramori.webp" }
  ];

  const SHINY_IDOLS = [
    { no: 1001, series: "shiny", attribute: "illumination STARS", group: "SHINY COLORS", jpName: "櫻木 真乃", name: "사쿠라기 마노", hex: "#ffbad6", image: "shiny/Mano_Sakuragi.webp" },
    { no: 1002, series: "shiny", attribute: "illumination STARS", group: "SHINY COLORS", jpName: "風野 灯織", name: "카자노 히오리", hex: "#144384", image: "shiny/Hiori_Kazano.webp" },
    { no: 1003, series: "shiny", attribute: "illumination STARS", group: "SHINY COLORS", jpName: "八宮 めぐる", name: "하치미야 메구루", hex: "#ffe012", image: "shiny/Meguru_Hachimiya.webp" },
    { no: 1004, series: "shiny", attribute: "L’Antica", group: "SHINY COLORS", jpName: "月岡 恋鐘", name: "츠키오카 코가네", hex: "#f84cad", image: "shiny/Kogane_Tsukioka.webp" },
    { no: 1005, series: "shiny", attribute: "L’Antica", group: "SHINY COLORS", jpName: "田中 摩美々", name: "타나카 마미미", hex: "#a846fb", image: "shiny/Mamimi_Tanaka.webp" },
    { no: 1006, series: "shiny", attribute: "L’Antica", group: "SHINY COLORS", jpName: "白瀬 咲耶", name: "시라세 사쿠야", hex: "#006047", image: "shiny/Sakuya_Shirase.webp" },
    { no: 1007, series: "shiny", attribute: "L’Antica", group: "SHINY COLORS", jpName: "三峰 結華", name: "미츠미네 유이카", hex: "#3b91c4", image: "shiny/Yuika_Mitsumine.webp" },
    { no: 1008, series: "shiny", attribute: "L’Antica", group: "SHINY COLORS", jpName: "幽谷 霧子", name: "유코쿠 키리코", hex: "#d9f2ff", image: "shiny/Kiriko_Yukoku.webp" },
    { no: 1009, series: "shiny", attribute: "Houkago Climax Girls", group: "SHINY COLORS", jpName: "小宮 果穂", name: "코미야 카호", hex: "#e5461c", image: "shiny/Kaho_Komiya.webp" },
    { no: 1010, series: "shiny", attribute: "Houkago Climax Girls", group: "SHINY COLORS", jpName: "園田 智代子", name: "소노다 치요코", hex: "#f93b90", image: "shiny/Chiyoko_Sonoda.webp" },
    { no: 1011, series: "shiny", attribute: "Houkago Climax Girls", group: "SHINY COLORS", jpName: "西城 樹里", name: "사이죠 쥬리", hex: "#ffc602", image: "shiny/Juri_Saijo.webp" },
    { no: 1012, series: "shiny", attribute: "Houkago Climax Girls", group: "SHINY COLORS", jpName: "杜野 凛世", name: "모리노 린제", hex: "#89c3eb", image: "shiny/Rinze_Morino.webp" },
    { no: 1013, series: "shiny", attribute: "Houkago Climax Girls", group: "SHINY COLORS", jpName: "有栖川 夏葉", name: "아리스가와 나츠하", hex: "#90e667", image: "shiny/Natsuha_Arisugawa.webp" },
    { no: 1014, series: "shiny", attribute: "ALSTROEMERIA", group: "SHINY COLORS", jpName: "大崎 甘奈", name: "오사키 아마나", hex: "#f54275", image: "shiny/Amana_Osaki.webp" },
    { no: 1015, series: "shiny", attribute: "ALSTROEMERIA", group: "SHINY COLORS", jpName: "大崎 甜花", name: "오사키 텐카", hex: "#e75bec", image: "shiny/Tenka_Osaki.webp" },
    { no: 1016, series: "shiny", attribute: "ALSTROEMERIA", group: "SHINY COLORS", jpName: "桑山 千雪", name: "쿠와야마 치유키", hex: "#fafafa", image: "shiny/Chiyuki_Kuwayama.webp" },
    { no: 1017, series: "shiny", attribute: "Straylight", group: "SHINY COLORS", jpName: "芹沢 あさひ", name: "세리자와 아사히", hex: "#f30100", image: "shiny/Asahi_Serizawa.webp" },
    { no: 1018, series: "shiny", attribute: "Straylight", group: "SHINY COLORS", jpName: "黛 冬優子", name: "마유즈미 후유코", hex: "#5aff19", image: "shiny/Fuyuko_Mayuzumi.webp" },
    { no: 1019, series: "shiny", attribute: "Straylight", group: "SHINY COLORS", jpName: "和泉 愛依", name: "이즈미 메이", hex: "#ff00ff", image: "shiny/Mei_Izumi.webp" },
    { no: 1020, series: "shiny", attribute: "noctchill", group: "SHINY COLORS", jpName: "浅倉 透", name: "아사쿠라 토오루", hex: "#50d0d0", image: "shiny/Toru_Asakura.webp" },
    { no: 1021, series: "shiny", attribute: "noctchill", group: "SHINY COLORS", jpName: "樋口 円香", name: "히구치 마도카", hex: "#be1e3e", image: "shiny/Madoka_Higuchi.webp" },
    { no: 1022, series: "shiny", attribute: "noctchill", group: "SHINY COLORS", jpName: "福丸 小糸", name: "후쿠마루 코이토", hex: "#7967c3", image: "shiny/Koito_Fukumaru.webp" },
    { no: 1023, series: "shiny", attribute: "noctchill", group: "SHINY COLORS", jpName: "市川 雛菜", name: "이치카와 히나나", hex: "#ffc639", image: "shiny/Hinana_Ichikawa.webp" },
    { no: 1024, series: "shiny", attribute: "SHHis", group: "SHINY COLORS", jpName: "七草 にちか", name: "나나쿠사 니치카", hex: "#a6cdb6", image: "shiny/Nichika_Nanakusa.webp" },
    { no: 1025, series: "shiny", attribute: "SHHis", group: "SHINY COLORS", jpName: "緋田 美琴", name: "아케타 미코토", hex: "#760f10", image: "shiny/Mikoto_Aketa.webp" },
    { no: 1026, series: "shiny", attribute: "CoMETIK", group: "SHINY COLORS", jpName: "斑鳩 ルカ", name: "이카루가 루카", hex: "#35281f", image: "shiny/Luca_Ikaruga.webp" },
    { no: 1027, series: "shiny", attribute: "CoMETIK", group: "SHINY COLORS", jpName: "鈴木 羽那", name: "스즈키 하나", hex: "#e0b5d3", image: "shiny/Hana_Suzuki.webp" },
    { no: 1028, series: "shiny", attribute: "CoMETIK", group: "SHINY COLORS", jpName: "郁田 はるき", name: "이쿠타 하루키", hex: "#ead7a4", image: "shiny/Haruki_Ikuta.webp" }
  ];

  const GAKUEN_IDOLS = [
    { no: 2001, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "花海 咲季", name: "하나미 사키", hex: "#e30f25", image: "gakuen/Saki_Hanami.webp" },
    { no: 2002, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "月村 手毬", name: "츠키무라 테마리", hex: "#0c7bbb", image: "gakuen/Temari_Tsukimura.webp" },
    { no: 2003, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "藤田 ことね", name: "후지타 코토네", hex: "#f8c112", image: "gakuen/Kotone_Fujita.webp" },
    { no: 2004, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "有村 麻央", name: "아리무라 마오", hex: "#7f1184", image: "gakuen/Mao_Arimura.webp" },
    { no: 2005, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "葛城 リーリヤ", name: "카츠라기 리리야", hex: "#eafdff", image: "gakuen/Lilja_Katsuragi.webp" },
    { no: 2006, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "倉本 千奈", name: "쿠라모토 치나", hex: "#f68b1f", image: "gakuen/China_Kuramoto.webp" },
    { no: 2007, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "紫雲 清夏", name: "시운 스미카", hex: "#7cfc00", image: "gakuen/Sumika_Shiun.webp" },
    { no: 2008, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "篠澤 広", name: "시노사와 히로", hex: "#00afcc", image: "gakuen/Hiro_Shinosawa.webp" },
    { no: 2009, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "姫崎 莉波", name: "히메사키 리나미", hex: "#f6adc6", image: "gakuen/Rinami_Himesaki.webp" },
    { no: 2010, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "花海 佑芽", name: "하나미 우메", hex: "#ea533a", image: "gakuen/Ume_Hanami.webp" },
    { no: 2011, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "秦谷 美鈴", name: "하타야 미스즈", hex: "#7a99cf", image: "gakuen/Misuzu_Hataya.webp" },
    { no: 2012, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "十王 星南", name: "주오 세나", hex: "#f6ae54", image: "gakuen/Sena_Juo.webp" },
    { no: 2013, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "雨夜 燕", name: "아마야 츠바메", hex: "#7b68ee", image: "gakuen/Tsubame_Amaya.webp" }
  ];

  const CINDERELLA_IDOLS = [
    { no: 3001, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "辻野あかり", name: "츠지노 아카리", hex: "#E10600", image: "cinderella/akari.webp" },
    { no: 3002, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "大沼くるみ", name: "오오누마 쿠루미", hex: "#FFC1BD", image: "cinderella/kurumi.webp" },
    { no: 3003, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "楊菲菲", name: "양 페이페이", hex: "#E56F66", image: "cinderella/yao.webp" },
    { no: 3004, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "関裕美", name: "세키 히로미", hex: "#FFB3AB", image: "cinderella/hiromi.webp" },
    { no: 3005, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "持田亜里沙", name: "모치다 아리사", hex: "#FD9286", image: "cinderella/arisa.webp" },
    { no: 3006, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "相原雪乃", name: "아이하라 유키노", hex: "#D06447", image: "cinderella/yukino.webp" },
    { no: 3007, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "安斎都", name: "안자이 미야코", hex: "#FA9063", image: "cinderella/miyako.webp" },
    { no: 3008, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "藤本里奈", name: "후지모토 리나", hex: "#623B2A", image: "cinderella/rina.webp" },
    { no: 3009, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "柳瀬美由紀", name: "야나세 미유키", hex: "#FF5D14", image: "cinderella/miyuki.webp" },
    { no: 3010, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "大原みちる", name: "오오하라 미치루", hex: "#D8843E", image: "cinderella/michiru.webp" },
    { no: 3011, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "クラリス", name: "클라리스", hex: "#FFDA7B", image: "cinderella/clarice.webp" },
    { no: 3012, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "榊原里美", name: "사카키바라 사토미", hex: "#FEC520", image: "cinderella/satomi.webp" },
    { no: 3013, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "日下部若葉", name: "쿠사카베 와카바", hex: "#C4D673", image: "cinderella/wakaba.webp" },
    { no: 3014, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "古賀小春", name: "코가 코하루", hex: "#C2E189", image: "cinderella/koharu.webp" },
    { no: 3015, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "緒方智絵里", name: "오가타 치에리", hex: "#6CC24A", image: "cinderella/chieri.webp" },
    { no: 3016, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "浅野風香", name: "아사노 후카", hex: "#618D75", image: "cinderella/fuka.webp" },
    { no: 3017, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "間中美里", name: "마나카 미사토", hex: "#D1F9E6", image: "cinderella/misato.webp" },
    { no: 3018, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "栗原ネネ", name: "쿠리하라 네네", hex: "#0F7BF8", image: "cinderella/nene.webp" },
    { no: 3019, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "輿水幸子", name: "코시미즈 사치코", hex: "#C1A0DA", image: "cinderella/sachiko.webp" },
    { no: 3020, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "柳清良", name: "야나기 키요라", hex: "#E7CBEE", image: "cinderella/kiyora.webp" },
    { no: 3021, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "白菊ほたる", name: "시라기쿠 호타루", hex: "#C964CF", image: "cinderella/hotaru.webp" },
    { no: 3022, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "今井加奈", name: "이마이 카나", hex: "#FF3DE5", image: "cinderella/kana.webp" },
    { no: 3023, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "早坂美玲", name: "하야사카 미레이", hex: "#C800A1", image: "cinderella/mirei.webp" },
    { no: 3024, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "中野有香", name: "나카노 유카", hex: "#E277CD", image: "cinderella/yuka.webp" },
    { no: 3025, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "小日向美穂", name: "코히나타 미호", hex: "#DB3EB1", image: "cinderella/miho.webp" },
    { no: 3026, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "水本ゆかり", name: "미즈모토 유카리", hex: "#EABEDB", image: "cinderella/yukari.webp" },
    { no: 3027, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "桃井あずき", name: "모모이 아즈키", hex: "#93256C", image: "cinderella/azuki.webp" },
    { no: 3028, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "櫻井桃華", name: "사쿠라이 모모카", hex: "#EF95CF", image: "cinderella/momoka.webp" },
    { no: 3029, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "宮本フレデリカ", name: "미야모토 프레데리카", hex: "#A20067", image: "cinderella/frederica.webp" },
    { no: 3030, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "遊佐こずえ", name: "유사 코즈에", hex: "#F4A6D7", image: "cinderella/kozue.webp" },
    { no: 3031, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "棟方愛海", name: "무나카타 아츠미", hex: "#C7579A", image: "cinderella/atsumi.webp" },
    { no: 3032, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "白雪千夜", name: "시라유키 치요", hex: "#EFD7E5", image: "cinderella/chiyo.webp" },
    { no: 3033, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "小早川紗枝", name: "코바야카와 사에", hex: "#E56DB1", image: "cinderella/sae.webp" },
    { no: 3034, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "佐久間まゆ", name: "사쿠마 마유", hex: "#DA1884", image: "cinderella/mayu.webp" },
    { no: 3035, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "松原早耶", name: "마츠바라 사야", hex: "#F743A6", image: "cinderella/saya.webp" },
    { no: 3036, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "大西由里子", name: "오오니시 유리코", hex: "#C90F74", image: "cinderella/yuriko.webp" },
    { no: 3037, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "太田優", name: "오오타 유우", hex: "#F851A7", image: "cinderella/yuu.webp" },
    { no: 3038, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "福山舞", name: "후쿠야마 마이", hex: "#FF68B5", image: "cinderella/mai.webp" },
    { no: 3039, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "一ノ瀬志希", name: "이치노세 시키", hex: "#A50050", image: "cinderella/shiki.webp" },
    { no: 3040, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "横山千佳", name: "요코야마 치카", hex: "#FC87BF", image: "cinderella/chika.webp" },
    { no: 3041, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "兵藤レナ", name: "효도 레나", hex: "#D8076B", image: "cinderella/rena.webp" },
    { no: 3042, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "涼宮星花", name: "스즈미야 세이카", hex: "#F994C4", image: "cinderella/seika.webp" },
    { no: 3043, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "安部菜々", name: "아베 나나", hex: "#EF4A81", image: "cinderella/nana.webp" },
    { no: 3044, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "赤西瑛梨華", name: "아카니시 에리카", hex: "#EB306D", image: "cinderella/erika.webp" },
    { no: 3045, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "双葉杏", name: "후타바 안즈", hex: "#F8A3BC", image: "cinderella/anzu.webp" },
    { no: 3046, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "島村卯月", name: "시마무라 우즈키", hex: "#F67599", image: "cinderella/uzuki.webp" },
    { no: 3047, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "前川みく", name: "마에카와 미쿠", hex: "#CE0037", image: "cinderella/miku.webp" },
    { no: 3048, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "井村雪菜", name: "이무라 세츠나", hex: "#ED3767", image: "cinderella/setsuna.webp" },
    { no: 3049, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "五十嵐響子", name: "이가라시 쿄코", hex: "#FABBCB", image: "cinderella/kyoko.webp" },
    { no: 3050, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "有浦柑奈", name: "아리우라 칸나", hex: "#EC4B6E", image: "cinderella/kanna.webp" },
    { no: 3051, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "丹羽仁美", name: "니와 히토미", hex: "#A80826", image: "cinderella/hitomi.webp" },
    { no: 3052, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "池袋晶葉", name: "이케부쿠로 아키하", hex: "#DE2F4D", image: "cinderella/akiha.webp" },
    { no: 3053, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "奥山沙織", name: "오쿠야마 사오리", hex: "#E87487", image: "cinderella/saori.webp" },
    { no: 3054, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "村松さくら", name: "무라마츠 사쿠라", hex: "#EB6174", image: "cinderella/sakura.webp" },
    { no: 3055, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "乙倉悠貴", name: "오토쿠라 유우키", hex: "#E4BEC3", image: "cinderella/yuuki.webp" },
    { no: 3056, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "三村かな子", name: "미무라 카나코", hex: "#FFB1BB", image: "cinderella/kanako.webp" },
    { no: 3057, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "椎名法子", name: "시이나 노리코", hex: "#F8485E", image: "cinderella/noriko.webp" },
    { no: 3058, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "工藤忍", name: "쿠도 시노부", hex: "#EB3249", image: "cinderella/shinobu.webp" },
    { no: 3059, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "西園寺琴歌", name: "사이온지 코토카", hex: "#E8CDD0", image: "cinderella/kotoka.webp" },
    { no: 3060, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "長富蓮実", name: "나가토미 하스미", hex: "#EA8A91", image: "cinderella/hasumi.webp" },
    { no: 3061, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "黒埼ちとせ", name: "쿠로사키 치토세", hex: "#EF3340", image: "cinderella/chitose.webp" },
    { no: 3062, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "江上椿", name: "에가미 츠바키", hex: "#E95B64", image: "cinderella/tsubaki.webp" },
    { no: 3063, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "道明寺歌鈴", name: "도묘지 카린", hex: "#D22630", image: "cinderella/karin.webp" },
    { no: 3064, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "月宮雅", name: "츠키미야 미야비", hex: "#FFD9DB", image: "cinderella/miyabi.webp" },
    { no: 3065, series: "cinderella", attribute: "Cute", group: "CINDERELLA GIRLS", jpName: "原田美世", name: "하라다 미요", hex: "#E94047", image: "cinderella/miyo.webp" },
    { no: 3066, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "黒川千秋", name: "쿠로카와 치아키", hex: "#BC1212", image: "cinderella/chiaki.webp" },
    { no: 3067, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "高橋礼子", name: "타카하시 레이코", hex: "#781000", image: "cinderella/reiko.webp" },
    { no: 3068, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "ヘレン", name: "헬렌", hex: "#C58E31", image: "cinderella/helen.webp" },
    { no: 3069, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "荒木比奈", name: "아라키 히나", hex: "#A0D884", image: "cinderella/hina.webp" },
    { no: 3070, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "氏家むつみ", name: "우지이에 무츠미", hex: "#375637", image: "cinderella/mutsumi.webp" },
    { no: 3071, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "大和亜季", name: "야마토 아키", hex: "#28724F", image: "cinderella/aki.webp" },
    { no: 3072, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "高垣楓", name: "타카가키 카에데", hex: "#47D7AC", image: "cinderella/kaede.webp" },
    { no: 3073, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "梅木音葉", name: "우메키 오토하", hex: "#75BBAE", image: "cinderella/otoha.webp" },
    { no: 3074, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "ライラ", name: "라이라", hex: "#7CE0D3", image: "cinderella/layla.webp" },
    { no: 3075, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "久川颯", name: "히사카와 하야테", hex: "#7EDDD3", image: "cinderella/hayate.webp" },
    { no: 3076, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "三船美優", name: "미후네 미유", hex: "#12BFB2", image: "cinderella/miyu.webp" },
    { no: 3077, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "結城晴", name: "유우키 하루", hex: "#71DAD4", image: "cinderella/haru.webp" },
    { no: 3078, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "北条加蓮", name: "호죠 카렌", hex: "#2AD2C9", image: "cinderella/karen.webp" },
    { no: 3079, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "森久保乃々", name: "모리쿠보 노노", hex: "#9CDBD9", image: "cinderella/nono.webp" },
    { no: 3080, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "瀬名詩織", name: "세나 시오리", hex: "#52C6C3", image: "cinderella/shiori.webp" },
    { no: 3081, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "望月聖", name: "모치즈키 히지리", hex: "#B7DDE1", image: "cinderella/hijiri.webp" },
    { no: 3082, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "水野翠", name: "미즈노 미도리", hex: "#43A0AB", image: "cinderella/midori.webp" },
    { no: 3083, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "浅利七海", name: "아사리 나나미", hex: "#009CBD", image: "cinderella/nanami.webp" },
    { no: 3084, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "大石泉", name: "오오이시 이즈미", hex: "#74D1EA", image: "cinderella/izumi.webp" },
    { no: 3085, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "岡崎泰葉", name: "오카자키 야스하", hex: "#ADE5F6", image: "cinderella/yasuha.webp" },
    { no: 3086, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "松尾千鶴", name: "마츠오 치즈루", hex: "#99E3FC", image: "cinderella/chizuru.webp" },
    { no: 3087, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "上条春菜", name: "카미죠 하루나", hex: "#5BC2E7", image: "cinderella/haruna.webp" },
    { no: 3088, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "新田美波", name: "닛타 미나미", hex: "#71C5E8", image: "cinderella/minami.webp" },
    { no: 3089, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "渋谷凛", name: "시부야 린", hex: "#009CDE", image: "cinderella/rin.webp" },
    { no: 3090, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "水木聖來", name: "미즈키 세이라", hex: "#86DBFF", image: "cinderella/seira.webp" },
    { no: 3091, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "高峯のあ", name: "타카미네 노아", hex: "#9FE1FD", image: "cinderella/noa.webp" },
    { no: 3092, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "多田李衣菜", name: "타다 리이나", hex: "#0077C8", image: "cinderella/riina.webp" },
    { no: 3093, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "塩見周子", name: "시오미 슈코", hex: "#DCE6ED", image: "cinderella/syuko.webp" },
    { no: 3094, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "佐々木千枝", name: "사사키 치에", hex: "#0072CE", image: "cinderella/chie.webp" },
    { no: 3095, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "砂塚あきら", name: "스나즈카 아키라", hex: "#7E93A7", image: "cinderella/akira.webp" },
    { no: 3096, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "白坂小梅", name: "시라사카 코우메", hex: "#ABCAE9", image: "cinderella/koume.webp" },
    { no: 3097, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "脇山珠美", name: "와키야마 타마미", hex: "#407EC9", image: "cinderella/tamami.webp" },
    { no: 3098, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "アナスタシア", name: "아나스타샤", hex: "#B1C9E8", image: "cinderella/anastasia.webp" },
    { no: 3099, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "速水奏", name: "하야미 카나데", hex: "#003087", image: "cinderella/kanade.webp" },
    { no: 3100, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "橘ありす", name: "타치바나 아리스", hex: "#5C88DA", image: "cinderella/arisu.webp" },
    { no: 3101, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "小室千奈美", name: "코무로 치나미", hex: "#ACC0E6", image: "cinderella/chinami.webp" },
    { no: 3102, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "成宮由愛", name: "나루미야 유메", hex: "#2B5CD5", image: "cinderella/yume.webp" },
    { no: 3103, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "鷺沢文香", name: "사기사와 후미카", hex: "#606EB2", image: "cinderella/fumika.webp" },
    { no: 3104, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "松本沙理奈", name: "마츠모토 사리나", hex: "#2943CB", image: "cinderella/sarina.webp" },
    { no: 3105, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "川島瑞樹", name: "카와시마 미즈키", hex: "#485CC7", image: "cinderella/mizuki.webp" },
    { no: 3106, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "和久井留美", name: "와쿠이 루미", hex: "#2E347E", image: "cinderella/rumi.webp" },
    { no: 3107, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "吉岡沙紀", name: "요시오카 사키", hex: "#1B24C2", image: "cinderella/saki.webp" },
    { no: 3108, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "佐城雪美", name: "사죠 유키미", hex: "#171C8F", image: "cinderella/yukimi.webp" },
    { no: 3109, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "藤原肇", name: "후지와라 하지메", hex: "#9595D2", image: "cinderella/hajime.webp" },
    { no: 3110, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "西川保奈美", name: "니시카와 호나미", hex: "#5756D8", image: "cinderella/honami.webp" },
    { no: 3111, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "八神マキノ", name: "야가미 마키노", hex: "#A6A4E0", image: "cinderella/makino.webp" },
    { no: 3112, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "古澤頼子", name: "후루사와 요리코", hex: "#3F3C8B", image: "cinderella/yoriko.webp" },
    { no: 3113, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "松永涼", name: "마츠나가 료", hex: "#211551", image: "cinderella/ryo.webp" },
    { no: 3114, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "神谷奈緒", name: "카미야 나오", hex: "#9678D3", image: "cinderella/nao.webp" },
    { no: 3115, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "服部瞳子", name: "핫토리 토코", hex: "#633AA1", image: "cinderella/toko.webp" },
    { no: 3116, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "二宮飛鳥", name: "니노미야 아스카", hex: "#5F259F", image: "cinderella/asuka.webp" },
    { no: 3117, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "篠原礼", name: "시노하라 레이", hex: "#BB68FE", image: "cinderella/rei.webp" },
    { no: 3118, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "藤居朋", name: "후지이 토모", hex: "#9B58C2", image: "cinderella/tomo.webp" },
    { no: 3119, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "伊集院惠", name: "이쥬인 메구미", hex: "#521078", image: "cinderella/megumi.webp" },
    { no: 3120, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "鷹富士茄子", name: "타카후지 카코", hex: "#5C068C", image: "cinderella/kako.webp" },
    { no: 3121, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "相川千夏", name: "아이카와 치나츠", hex: "#7A508F", image: "cinderella/chinatsu.webp" },
    { no: 3122, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "綾瀬穂乃香", name: "아야세 호노카", hex: "#F5D6FF", image: "cinderella/honoka.webp" },
    { no: 3123, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "桐生つかさ", name: "키류 츠카사", hex: "#AB4EC6", image: "cinderella/tsukasa.webp" },
    { no: 3124, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "神崎蘭子", name: "칸자키 란코", hex: "#84329B", image: "cinderella/ranko.webp" },
    { no: 3125, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "岸部彩華", name: "키시베 아야카", hex: "#F14FEE", image: "cinderella/ayaka.webp" },
    { no: 3126, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "柊志乃", name: "히이라기 시노", hex: "#AD1E66", image: "cinderella/shino.webp" },
    { no: 3127, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "桐野アヤ", name: "키리노 아야", hex: "#C3396C", image: "cinderella/aya.webp" },
    { no: 3128, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "東郷あい", name: "토고 아이", hex: "#9B274A", image: "cinderella/ai.webp" },
    { no: 3129, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "ケイト", name: "케이트", hex: "#CF142B", image: "cinderella/kate.webp" },
    { no: 3130, series: "cinderella", attribute: "Cool", group: "CINDERELLA GIRLS", jpName: "木場真奈美", name: "키바 마나미", hex: "#8D8696", image: "cinderella/manami.webp" },
    { no: 3131, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "日野茜", name: "히노 아카네", hex: "#F9423A", image: "cinderella/akane.webp" },
    { no: 3132, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "難波笑美", name: "난바 에미", hex: "#E03C31", image: "cinderella/emi.webp" },
    { no: 3133, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "ナターリア", name: "나탈리아", hex: "#F4633A", image: "cinderella/natalia.webp" },
    { no: 3134, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "西島櫂", name: "니시지마 카이", hex: "#F16029", image: "cinderella/kai.webp" },
    { no: 3135, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "片桐早苗", name: "카타기리 사나에", hex: "#FC4C02", image: "cinderella/sanae.webp" },
    { no: 3136, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "槙原志保", name: "마키하라 시호", hex: "#F97F4B", image: "cinderella/shiho.webp" },
    { no: 3137, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "野々村そら", name: "노노무라 소라", hex: "#FC6E2E", image: "cinderella/sora.webp" },
    { no: 3138, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "矢口美羽", name: "야구치 미우", hex: "#EC5800", image: "cinderella/miu.webp" },
    { no: 3139, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "松山久美子", name: "마츠야마 쿠미코", hex: "#FF7B2C", image: "cinderella/kumiko.webp" },
    { no: 3140, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "依田芳乃", name: "요리타 요시노", hex: "#C4BCB7", image: "cinderella/yoshino.webp" },
    { no: 3141, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "堀裕子", name: "호리 유코", hex: "#ECA154", image: "cinderella/yuko.webp" },
    { no: 3142, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "沢田麻理菜", name: "사와다 마리나", hex: "#FCA538", image: "cinderella/marina.webp" },
    { no: 3143, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "城ヶ崎美嘉", name: "죠가사키 미카", hex: "#FE9D1A", image: "cinderella/mika.webp" },
    { no: 3144, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "姫川友紀", name: "히메카와 유키", hex: "#ED8B00", image: "cinderella/yuki.webp" },
    { no: 3145, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "土屋亜子", name: "츠치야 아코", hex: "#FFBE60", image: "cinderella/ako.webp" },
    { no: 3146, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "上田鈴帆", name: "우에다 스즈호", hex: "#CC8A00", image: "cinderella/suzuho.webp" },
    { no: 3147, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "本田未央", name: "혼다 미오", hex: "#FFB81C", image: "cinderella/mio.webp" },
    { no: 3148, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "相馬夏美", name: "소마 나츠미", hex: "#FCC138", image: "cinderella/natsumi.webp" },
    { no: 3149, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "冴島清美", name: "사에지마 키요미", hex: "#F6BD30", image: "cinderella/kiyomi.webp" },
    { no: 3150, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "愛野渚", name: "아이노 나기사", hex: "#FFCB49", image: "cinderella/nagisa.webp" },
    { no: 3151, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "大槻唯", name: "오오츠키 유이", hex: "#F6BE00", image: "cinderella/yui.webp" },
    { no: 3152, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "市原仁奈", name: "이치하라 니나", hex: "#F8E08E", image: "cinderella/nina.webp" },
    { no: 3153, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "喜多日菜子", name: "키타 히나코", hex: "#FCD757", image: "cinderella/hinako.webp" },
    { no: 3154, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "並木芽衣子", name: "나미키 메이코", hex: "#FEEA9C", image: "cinderella/meiko.webp" },
    { no: 3155, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "赤城みりあ", name: "아카기 미리아", hex: "#FFCD00", image: "cinderella/miria.webp" },
    { no: 3156, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "諸星きらり", name: "모로보시 키라리", hex: "#FFD100", image: "cinderella/kirari.webp" },
    { no: 3157, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "龍崎薫", name: "류자키 카오루", hex: "#FAE053", image: "cinderella/kaoru.webp" },
    { no: 3158, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "首藤葵", name: "슈토 아오이", hex: "#FBE983", image: "cinderella/aoi.webp" },
    { no: 3159, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "キャシー・グラハム", name: "캐시 그라함", hex: "#FFDC00", image: "cinderella/cathy.webp" },
    { no: 3160, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "城ヶ崎莉嘉", name: "죠가사키 리카", hex: "#FEDD00", image: "cinderella/rika.webp" },
    { no: 3161, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "相葉夕美", name: "아이바 유미", hex: "#F0E991", image: "cinderella/yumi.webp" },
    { no: 3162, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "喜多見柚", name: "키타미 유즈", hex: "#F8F283", image: "cinderella/yuzu.webp" },
    { no: 3163, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "小松伊吹", name: "코마츠 이부키", hex: "#FFFB4E", image: "cinderella/ibuki.webp" },
    { no: 3164, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "若林智香", name: "와카바야시 토모카", hex: "#FDFF4E", image: "cinderella/tomoka.webp" },
    { no: 3165, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "海老原菜帆", name: "에비하라 나호", hex: "#819832", image: "cinderella/naho.webp" },
    { no: 3166, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "高森藍子", name: "타카모리 아이코", hex: "#CDEA80", image: "cinderella/aiko.webp" },
    { no: 3167, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "斉藤洋子", name: "사이토 요코", hex: "#CBFC9F", image: "cinderella/yoko.webp" },
    { no: 3168, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "三好紗南", name: "미요시 사나", hex: "#45F05B", image: "cinderella/sana.webp" },
    { no: 3169, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "北川真尋", name: "키타가와 마히로", hex: "#4FD962", image: "cinderella/mahiro.webp" },
    { no: 3170, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "真鍋いつき", name: "마나베 이츠키", hex: "#58EABD", image: "cinderella/itsuki.webp" },
    { no: 3171, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "浜口あやめ", name: "하마구치 아야메", hex: "#440099", image: "cinderella/ayame.webp" },
    { no: 3172, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "イヴ・サンタクロース", name: "이브 산타클로스", hex: "#E5E1E6", image: "cinderella/eve.webp" },
    { no: 3173, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "小関麗奈", name: "코세키 레이나", hex: "#9B26B6", image: "cinderella/reina.webp" },
    { no: 3174, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "メアリー・コクラン", name: "메어리 코크란", hex: "#F196FF", image: "cinderella/mary.webp" },
    { no: 3175, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "夢見りあむ", name: "유메미 리아무", hex: "#E89CDC", image: "cinderella/riamu.webp" },
    { no: 3176, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "向井拓海", name: "무카이 타쿠미", hex: "#B0008E", image: "cinderella/takumi.webp" },
    { no: 3177, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "浜川愛結奈", name: "하마카와 아유나", hex: "#A42678", image: "cinderella/ayuna.webp" },
    { no: 3178, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "的場梨沙", name: "마토바 리사", hex: "#FF00A0", image: "cinderella/risa.webp" },
    { no: 3179, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "仙崎恵磨", name: "센자키 에마", hex: "#D30D85", image: "cinderella/ema.webp" },
    { no: 3180, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "衛藤美紗希", name: "에토 미사키", hex: "#FE85C7", image: "cinderella/misaki.webp" },
    { no: 3181, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "佐藤心", name: "사토 신", hex: "#F04E98", image: "cinderella/shin.webp" },
    { no: 3182, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "財前時子", name: "자이젠 토키코", hex: "#7D0837", image: "cinderella/tokiko.webp" },
    { no: 3183, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "星輝子", name: "호시 쇼코", hex: "#A6093D", image: "cinderella/syoko.webp" },
    { no: 3184, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "久川凪", name: "히사카와 나기", hex: "#F8A4BD", image: "cinderella/nagi.webp" },
    { no: 3185, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "杉坂海", name: "스기사카 우미", hex: "#D83C6A", image: "cinderella/umi.webp" },
    { no: 3186, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "南条光", name: "난죠 히카루", hex: "#E4002B", image: "cinderella/hikaru.webp" },
    { no: 3187, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "十時愛梨", name: "토토키 아이리", hex: "#DF4661", image: "cinderella/airi.webp" },
    { no: 3188, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "村上巴", name: "무라카미 토모에", hex: "#AB192C", image: "cinderella/tomoe.webp" },
    { no: 3189, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "木村夏樹", name: "키무라 나츠키", hex: "#53565A", image: "cinderella/natsuki.webp" },
    { no: 3190, series: "cinderella", attribute: "Passion", group: "CINDERELLA GIRLS", jpName: "及川雫", name: "오이카와 시즈쿠", hex: "#FFFFFF", image: "cinderella/shizuku.webp" }
  ];

  const SERIES_IDOLS = Object.freeze({
    allstars: ALLSTARS_IDOLS,
    million: MILLION_IDOLS,
    shiny: SHINY_IDOLS,
    gakuen: GAKUEN_IDOLS,
    cinderella: CINDERELLA_IDOLS
  });

  const ALLSTARS_IMAGE_FILES = {
    1: "allstars/Haruka_Amami.webp",
    2: "allstars/Chihaya_Kisaragi.webp",
    3: "allstars/Miki_Hoshii.webp",
    4: "allstars/Yukiho_Hagiwara.webp",
    5: "allstars/Yayoi_Takatsuki.webp",
    6: "allstars/Makoto_Kikuchi.webp",
    7: "allstars/Iori_Minase.webp",
    8: "allstars/Takane_Shijou.webp",
    9: "allstars/Ritsuko_Akizuki.webp",
    10: "allstars/Azusa_Miura.webp",
    11: "allstars/Ami_Futami.webp",
    12: "allstars/Mami_Futami.webp",
    13: "allstars/Hibiki_Ganaha.webp"
  };

  const MILLION_IMAGE_FILES = {
    14: "million/Mirai_Kasuga.webp",
    15: "million/Shizuka_Mogami.webp",
    16: "million/Tsubasa_Ibuki.webp",
    17: "million/Kotoha_Tanaka.webp",
    18: "million/Elena_Shimabara.webp",
    19: "million/Minako_Satake.webp",
    20: "million/Megumi_Tokoro.webp",
    21: "million/Matsuri_Tokugawa.webp",
    22: "million/Serika_Hakozaki.webp",
    23: "million/Akane_Nonohara.webp",
    24: "million/Anna_Mochizuki.webp",
    25: "million/Roco.webp",
    26: "million/Yuriko_Nanao.webp",
    27: "million/Sayoko_Takayama.webp",
    28: "million/Arisa_Matsuda.webp",
    29: "million/Umi_Kousaka.webp",
    30: "million/Iku_Nakatani.webp",
    31: "million/Tomoka_Tenkubashi.webp",
    32: "million/Emily_Stewart.webp",
    33: "million/Shiho_Kitazawa.webp",
    34: "million/Ayumu_Maihama.webp",
    35: "million/Hinata_Kinoshita.webp",
    36: "million/Kana_Yabuki.webp",
    37: "million/Nao_Yokoyama.webp",
    38: "million/Chizuru_Nikaido.webp",
    39: "million/Konomi_Baba.webp",
    40: "million/Tamaki_Ogami.webp",
    41: "million/Fuka_Toyokawa.webp",
    42: "million/Miya_Miake.webp",
    43: "million/Noriko_Fukuda.webp",
    44: "million/Mizuki_Makabe.webp",
    45: "million/Karen_Shinomiya.webp",
    46: "million/Rio_Momose.webp",
    47: "million/Subaru_Nagayoshi.webp",
    48: "million/Reika_Kitakami.webp",
    49: "million/Momoko_Suou.webp",
    50: "million/Julia.webp",
    51: "million/Tsumugi_Shirokane.webp",
    52: "million/Kaori_Sakuramori.webp"
  };

  const SHINY_IMAGE_FILES = {
    1001: "shiny/Mano_Sakuragi.webp",
    1002: "shiny/Hiori_Kazano.webp",
    1003: "shiny/Meguru_Hachimiya.webp",
    1004: "shiny/Kogane_Tsukioka.webp",
    1005: "shiny/Mamimi_Tanaka.webp",
    1006: "shiny/Sakuya_Shirase.webp",
    1007: "shiny/Yuika_Mitsumine.webp",
    1008: "shiny/Kiriko_Yukoku.webp",
    1009: "shiny/Kaho_Komiya.webp",
    1010: "shiny/Chiyoko_Sonoda.webp",
    1011: "shiny/Juri_Saijo.webp",
    1012: "shiny/Rinze_Morino.webp",
    1013: "shiny/Natsuha_Arisugawa.webp",
    1014: "shiny/Amana_Osaki.webp",
    1015: "shiny/Tenka_Osaki.webp",
    1016: "shiny/Chiyuki_Kuwayama.webp",
    1017: "shiny/Asahi_Serizawa.webp",
    1018: "shiny/Fuyuko_Mayuzumi.webp",
    1019: "shiny/Mei_Izumi.webp",
    1020: "shiny/Toru_Asakura.webp",
    1021: "shiny/Madoka_Higuchi.webp",
    1022: "shiny/Koito_Fukumaru.webp",
    1023: "shiny/Hinana_Ichikawa.webp",
    1024: "shiny/Nichika_Nanakusa.webp",
    1025: "shiny/Mikoto_Aketa.webp",
    1026: "shiny/Luca_Ikaruga.webp",
    1027: "shiny/Hana_Suzuki.webp",
    1028: "shiny/Haruki_Ikuta.webp"
  };

  const GAKUEN_IMAGE_FILES = {
    2001: "gakuen/Saki_Hanami.webp",
    2002: "gakuen/Temari_Tsukimura.webp",
    2003: "gakuen/Kotone_Fujita.webp",
    2004: "gakuen/Mao_Arimura.webp",
    2005: "gakuen/Lilja_Katsuragi.webp",
    2006: "gakuen/China_Kuramoto.webp",
    2007: "gakuen/Sumika_Shiun.webp",
    2008: "gakuen/Hiro_Shinosawa.webp",
    2009: "gakuen/Rinami_Himesaki.webp",
    2010: "gakuen/Ume_Hanami.webp",
    2011: "gakuen/Misuzu_Hataya.webp",
    2012: "gakuen/Sena_Juo.webp",
    2013: "gakuen/Tsubame_Amaya.webp"
  };

  const CINDERELLA_IMAGE_FILES = {
    3001: "cinderella/akari.webp",
    3002: "cinderella/kurumi.webp",
    3003: "cinderella/yao.webp",
    3004: "cinderella/hiromi.webp",
    3005: "cinderella/arisa.webp",
    3006: "cinderella/yukino.webp",
    3007: "cinderella/miyako.webp",
    3008: "cinderella/rina.webp",
    3009: "cinderella/miyuki.webp",
    3010: "cinderella/michiru.webp",
    3011: "cinderella/clarice.webp",
    3012: "cinderella/satomi.webp",
    3013: "cinderella/wakaba.webp",
    3014: "cinderella/koharu.webp",
    3015: "cinderella/chieri.webp",
    3016: "cinderella/fuka.webp",
    3017: "cinderella/misato.webp",
    3018: "cinderella/nene.webp",
    3019: "cinderella/sachiko.webp",
    3020: "cinderella/kiyora.webp",
    3021: "cinderella/hotaru.webp",
    3022: "cinderella/kana.webp",
    3023: "cinderella/mirei.webp",
    3024: "cinderella/yuka.webp",
    3025: "cinderella/miho.webp",
    3026: "cinderella/yukari.webp",
    3027: "cinderella/azuki.webp",
    3028: "cinderella/momoka.webp",
    3029: "cinderella/frederica.webp",
    3030: "cinderella/kozue.webp",
    3031: "cinderella/atsumi.webp",
    3032: "cinderella/chiyo.webp",
    3033: "cinderella/sae.webp",
    3034: "cinderella/mayu.webp",
    3035: "cinderella/saya.webp",
    3036: "cinderella/yuriko.webp",
    3037: "cinderella/yuu.webp",
    3038: "cinderella/mai.webp",
    3039: "cinderella/shiki.webp",
    3040: "cinderella/chika.webp",
    3041: "cinderella/rena.webp",
    3042: "cinderella/seika.webp",
    3043: "cinderella/nana.webp",
    3044: "cinderella/erika.webp",
    3045: "cinderella/anzu.webp",
    3046: "cinderella/uzuki.webp",
    3047: "cinderella/miku.webp",
    3048: "cinderella/setsuna.webp",
    3049: "cinderella/kyoko.webp",
    3050: "cinderella/kanna.webp",
    3051: "cinderella/hitomi.webp",
    3052: "cinderella/akiha.webp",
    3053: "cinderella/saori.webp",
    3054: "cinderella/sakura.webp",
    3055: "cinderella/yuuki.webp",
    3056: "cinderella/kanako.webp",
    3057: "cinderella/noriko.webp",
    3058: "cinderella/shinobu.webp",
    3059: "cinderella/kotoka.webp",
    3060: "cinderella/hasumi.webp",
    3061: "cinderella/chitose.webp",
    3062: "cinderella/tsubaki.webp",
    3063: "cinderella/karin.webp",
    3064: "cinderella/miyabi.webp",
    3065: "cinderella/miyo.webp",
    3066: "cinderella/chiaki.webp",
    3067: "cinderella/reiko.webp",
    3068: "cinderella/helen.webp",
    3069: "cinderella/hina.webp",
    3070: "cinderella/mutsumi.webp",
    3071: "cinderella/aki.webp",
    3072: "cinderella/kaede.webp",
    3073: "cinderella/otoha.webp",
    3074: "cinderella/layla.webp",
    3075: "cinderella/hayate.webp",
    3076: "cinderella/miyu.webp",
    3077: "cinderella/haru.webp",
    3078: "cinderella/karen.webp",
    3079: "cinderella/nono.webp",
    3080: "cinderella/shiori.webp",
    3081: "cinderella/hijiri.webp",
    3082: "cinderella/midori.webp",
    3083: "cinderella/nanami.webp",
    3084: "cinderella/izumi.webp",
    3085: "cinderella/yasuha.webp",
    3086: "cinderella/chizuru.webp",
    3087: "cinderella/haruna.webp",
    3088: "cinderella/minami.webp",
    3089: "cinderella/rin.webp",
    3090: "cinderella/seira.webp",
    3091: "cinderella/noa.webp",
    3092: "cinderella/riina.webp",
    3093: "cinderella/syuko.webp",
    3094: "cinderella/chie.webp",
    3095: "cinderella/akira.webp",
    3096: "cinderella/koume.webp",
    3097: "cinderella/tamami.webp",
    3098: "cinderella/anastasia.webp",
    3099: "cinderella/kanade.webp",
    3100: "cinderella/arisu.webp",
    3101: "cinderella/chinami.webp",
    3102: "cinderella/yume.webp",
    3103: "cinderella/fumika.webp",
    3104: "cinderella/sarina.webp",
    3105: "cinderella/mizuki.webp",
    3106: "cinderella/rumi.webp",
    3107: "cinderella/saki.webp",
    3108: "cinderella/yukimi.webp",
    3109: "cinderella/hajime.webp",
    3110: "cinderella/honami.webp",
    3111: "cinderella/makino.webp",
    3112: "cinderella/yoriko.webp",
    3113: "cinderella/ryo.webp",
    3114: "cinderella/nao.webp",
    3115: "cinderella/toko.webp",
    3116: "cinderella/asuka.webp",
    3117: "cinderella/rei.webp",
    3118: "cinderella/tomo.webp",
    3119: "cinderella/megumi.webp",
    3120: "cinderella/kako.webp",
    3121: "cinderella/chinatsu.webp",
    3122: "cinderella/honoka.webp",
    3123: "cinderella/tsukasa.webp",
    3124: "cinderella/ranko.webp",
    3125: "cinderella/ayaka.webp",
    3126: "cinderella/shino.webp",
    3127: "cinderella/aya.webp",
    3128: "cinderella/ai.webp",
    3129: "cinderella/kate.webp",
    3130: "cinderella/manami.webp",
    3131: "cinderella/akane.webp",
    3132: "cinderella/emi.webp",
    3133: "cinderella/natalia.webp",
    3134: "cinderella/kai.webp",
    3135: "cinderella/sanae.webp",
    3136: "cinderella/shiho.webp",
    3137: "cinderella/sora.webp",
    3138: "cinderella/miu.webp",
    3139: "cinderella/kumiko.webp",
    3140: "cinderella/yoshino.webp",
    3141: "cinderella/yuko.webp",
    3142: "cinderella/marina.webp",
    3143: "cinderella/mika.webp",
    3144: "cinderella/yuki.webp",
    3145: "cinderella/ako.webp",
    3146: "cinderella/suzuho.webp",
    3147: "cinderella/mio.webp",
    3148: "cinderella/natsumi.webp",
    3149: "cinderella/kiyomi.webp",
    3150: "cinderella/nagisa.webp",
    3151: "cinderella/yui.webp",
    3152: "cinderella/nina.webp",
    3153: "cinderella/hinako.webp",
    3154: "cinderella/meiko.webp",
    3155: "cinderella/miria.webp",
    3156: "cinderella/kirari.webp",
    3157: "cinderella/kaoru.webp",
    3158: "cinderella/aoi.webp",
    3159: "cinderella/cathy.webp",
    3160: "cinderella/rika.webp",
    3161: "cinderella/yumi.webp",
    3162: "cinderella/yuzu.webp",
    3163: "cinderella/ibuki.webp",
    3164: "cinderella/tomoka.webp",
    3165: "cinderella/naho.webp",
    3166: "cinderella/aiko.webp",
    3167: "cinderella/yoko.webp",
    3168: "cinderella/sana.webp",
    3169: "cinderella/mahiro.webp",
    3170: "cinderella/itsuki.webp",
    3171: "cinderella/ayame.webp",
    3172: "cinderella/eve.webp",
    3173: "cinderella/reina.webp",
    3174: "cinderella/mary.webp",
    3175: "cinderella/riamu.webp",
    3176: "cinderella/takumi.webp",
    3177: "cinderella/ayuna.webp",
    3178: "cinderella/risa.webp",
    3179: "cinderella/ema.webp",
    3180: "cinderella/misaki.webp",
    3181: "cinderella/shin.webp",
    3182: "cinderella/tokiko.webp",
    3183: "cinderella/syoko.webp",
    3184: "cinderella/nagi.webp",
    3185: "cinderella/umi.webp",
    3186: "cinderella/hikaru.webp",
    3187: "cinderella/airi.webp",
    3188: "cinderella/tomoe.webp",
    3189: "cinderella/natsuki.webp",
    3190: "cinderella/shizuku.webp"
  };

  const SERIES_IMAGE_FILES = Object.freeze({
    allstars: ALLSTARS_IMAGE_FILES,
    million: MILLION_IMAGE_FILES,
    shiny: SHINY_IMAGE_FILES,
    gakuen: GAKUEN_IMAGE_FILES,
    cinderella: CINDERELLA_IMAGE_FILES
  });

  const ALLSTARS_HAIR_COLORS = {
    1: "#8E5049",
    2: "#28355A",
    3: "#F2E48E",
    4: "#C8925E",
    5: "#D88445",
    6: "#3D3C46",
    7: "#9A6643",
    8: "#D9D8E6",
    9: "#8A6043",
    10: "#303A6C",
    11: "#A17542",
    12: "#A17542",
    13: "#242633"
  };

  const MILLION_HAIR_COLORS = {
    14: "#754842",
    15: "#283257",
    16: "#D1A649",
    17: "#A04C41",
    18: "#CBDAA2",
    19: "#674D3F",
    20: "#9A6D3D",
    21: "#72B0B0",
    22: "#B58A61",
    23: "#E46A47",
    24: "#675E8F",
    25: "#C9C0B8",
    26: "#4973A2",
    27: "#8C8179",
    28: "#4C2626",
    29: "#9A6A35",
    30: "#4C352F",
    31: "#D4AE76",
    32: "#E2C95D",
    33: "#826A5C",
    34: "#EA60AB",
    35: "#683F32",
    36: "#CF843D",
    37: "#845743",
    38: "#5B3C24",
    39: "#A26C3F",
    40: "#D96B45",
    41: "#576496",
    42: "#B9915A",
    43: "#E2BE4F",
    44: "#DBC2E5",
    45: "#D8B863",
    46: "#E7BB5D",
    47: "#868159",
    48: "#334A5A",
    49: "#9B764B",
    50: "#B1382F",
    51: "#D6E7FA",
    52: "#95887C"
  };

  const SHINY_HAIR_COLORS = {
    1001: "#C99F8E",
    1002: "#31363C",
    1003: "#F8E699",
    1004: "#967B7B",
    1005: "#4A3458",
    1006: "#433846",
    1007: "#3B3344",
    1008: "#B7AAB0",
    1009: "#CA797E",
    1010: "#866662",
    1011: "#F8DC9D",
    1012: "#535977",
    1013: "#EF9B8A",
    1014: "#9A5A5C",
    1015: "#A76868",
    1016: "#7C684E",
    1017: "#E1D0C7",
    1018: "#4D4D5C",
    1019: "#89502E",
    1020: "#A1869D",
    1021: "#98353E",
    1022: "#4D4A66",
    1023: "#D0AF9A",
    1024: "#919172",
    1025: "#985143",
    1026: "#403939",
    1027: "#B3B9EC",
    1028: "#E2BBB7"
  };

  const GAKUEN_HAIR_COLORS = {
    2001: "#CF7E7E",
    2002: "#5F6E73",
    2003: "#E7C95E",
    2004: "#D5A9B1",
    2005: "#E6DBDB",
    2006: "#887B70",
    2007: "#E7A25B",
    2008: "#EBDFCC",
    2009: "#D3A495",
    2010: "#B47A63",
    2011: "#5E577D",
    2012: "#FFF1DC",
    2013: "#83818D"
  };

  const CINDERELLA_HAIR_COLORS = {
    3001: "#6D4641",
    3002: "#6D6B7A",
    3003: "#6B5572",
    3004: "#85443D",
    3005: "#8B6651",
    3006: "#7B5542",
    3007: "#B27F4C",
    3008: "#F1C95B",
    3009: "#66554A",
    3010: "#925A47",
    3011: "#EFB25C",
    3012: "#A39297",
    3013: "#906458",
    3014: "#BA1E57",
    3015: "#995D5F",
    3016: "#59514B",
    3017: "#4F404C",
    3018: "#5A5655",
    3019: "#C5B5D0",
    3020: "#E6C7F1",
    3021: "#5F4F72",
    3022: "#716653",
    3023: "#6C5E8A",
    3024: "#40362C",
    3025: "#504E4C",
    3026: "#7A5744",
    3027: "#574C4B",
    3028: "#E98D58",
    3029: "#F8DC5F",
    3030: "#F9FFC1",
    3031: "#955756",
    3032: "#5F5E66",
    3033: "#817476",
    3034: "#88604C",
    3035: "#6D7573",
    3036: "#B7653A",
    3037: "#9D683F",
    3038: "#5B554E",
    3039: "#7C4A5B",
    3040: "#91694B",
    3041: "#825B42",
    3042: "#6A645B",
    3043: "#B14637",
    3044: "#604935",
    3045: "#E1E7FE",
    3046: "#644D3F",
    3047: "#7F5D49",
    3048: "#A64E44",
    3049: "#AE5B53",
    3050: "#664341",
    3051: "#475247",
    3052: "#BE7E58",
    3053: "#69503D",
    3054: "#5E4139",
    3055: "#92858F",
    3056: "#865B49",
    3057: "#AD605D",
    3058: "#A97650",
    3059: "#DE8782",
    3060: "#895843",
    3061: "#E4D768",
    3062: "#4C4D60",
    3063: "#604120",
    3064: "#79513C",
    3065: "#473B32",
    3066: "#584E51",
    3067: "#4B3B39",
    3068: "#282630",
    3069: "#CC754C",
    3070: "#413634",
    3071: "#4B5C41",
    3072: "#9E976F",
    3073: "#ADE1DD",
    3074: "#EADA94",
    3075: "#D8D4CE",
    3076: "#864A4E",
    3077: "#EDA155",
    3078: "#AC4842",
    3079: "#967A57",
    3080: "#706168",
    3081: "#F9CC4F",
    3082: "#50546B",
    3083: "#7680C6",
    3084: "#455D60",
    3085: "#364F6B",
    3086: "#524845",
    3087: "#584C50",
    3088: "#7F4D33",
    3089: "#574537",
    3090: "#815146",
    3091: "#BCC8D2",
    3092: "#303351",
    3093: "#22223E",
    3094: "#574A48",
    3095: "#594948",
    3096: "#534140",
    3097: "#764653",
    3098: "#D3C8C1",
    3099: "#646C7F",
    3100: "#645351",
    3101: "#76503D",
    3102: "#B4B6B6",
    3103: "#49413E",
    3104: "#C08C5D",
    3105: "#91594A",
    3106: "#515E80",
    3107: "#BD6243",
    3108: "#4B588D",
    3109: "#63595B",
    3110: "#78585C",
    3111: "#9F657B",
    3112: "#834339",
    3113: "#C49A5D",
    3114: "#745247",
    3115: "#8F6463",
    3116: "#7C7678",
    3117: "#744948",
    3118: "#657467",
    3119: "#91694C",
    3120: "#4E3F3A",
    3121: "#784F5D",
    3122: "#4A352C",
    3123: "#E8815B",
    3124: "#A39F9E",
    3125: "#7D5830",
    3126: "#3C393E",
    3127: "#434F44",
    3128: "#4D423C",
    3129: "#9F6B5B",
    3130: "#A45A4C",
    3131: "#C0812D",
    3132: "#B26B51",
    3133: "#4C5C4D",
    3134: "#A95E3F",
    3135: "#B46E4A",
    3136: "#B37F48",
    3137: "#675B51",
    3138: "#525355",
    3139: "#835042",
    3140: "#886857",
    3141: "#907B67",
    3142: "#A16364",
    3143: "#F3A89D",
    3144: "#603A37",
    3145: "#A98455",
    3146: "#224129",
    3147: "#97604B",
    3148: "#4A3D38",
    3149: "#584F47",
    3150: "#926651",
    3151: "#D6874F",
    3152: "#B35D42",
    3153: "#784041",
    3154: "#7C644F",
    3155: "#675252",
    3156: "#E79C62",
    3157: "#B35648",
    3158: "#42564B",
    3159: "#DA9240",
    3160: "#845B69",
    3161: "#B06B40",
    3162: "#905241",
    3163: "#E98C64",
    3164: "#BC4F42",
    3165: "#4B4045",
    3166: "#7F5D40",
    3167: "#915649",
    3168: "#6A637F",
    3169: "#7E5D47",
    3170: "#89593F",
    3171: "#5A4E44",
    3172: "#3D4A81",
    3173: "#8E6964",
    3174: "#EBD780",
    3175: "#FBC4D6",
    3176: "#494035",
    3177: "#D8756A",
    3178: "#4E4948",
    3179: "#4E4256",
    3180: "#63422B",
    3181: "#AE7858",
    3182: "#CB6D54",
    3183: "#D6C5C6",
    3184: "#E07269",
    3185: "#534E57",
    3186: "#27595D",
    3187: "#955D44",
    3188: "#B92D33",
    3189: "#82583F",
    3190: "#5C4249"
  };

  const SERIES_HAIR_COLORS = Object.freeze({
    allstars: ALLSTARS_HAIR_COLORS,
    million: MILLION_HAIR_COLORS,
    shiny: SHINY_HAIR_COLORS,
    gakuen: GAKUEN_HAIR_COLORS,
    cinderella: CINDERELLA_HAIR_COLORS
  });

  const sortByNo = (left, right) => left.no - right.no;
  const IDOLS = [...ALLSTARS_IDOLS, ...MILLION_IDOLS].sort(sortByNo);
  const ADDITIONAL_IDOLS = [...SHINY_IDOLS, ...GAKUEN_IDOLS, ...CINDERELLA_IDOLS].sort(sortByNo);
  const ALL_IDOLS = [...IDOLS, ...ADDITIONAL_IDOLS];

  const IDOL_IMAGE_FILES = Object.freeze({
    ...ALLSTARS_IMAGE_FILES,
    ...MILLION_IMAGE_FILES,
    ...SHINY_IMAGE_FILES,
    ...GAKUEN_IMAGE_FILES,
    ...CINDERELLA_IMAGE_FILES,
  });

  const HAIR_COLORS = Object.freeze({
    ...ALLSTARS_HAIR_COLORS,
    ...MILLION_HAIR_COLORS
  });

  const ADDITIONAL_HAIR_COLORS = Object.freeze({
    ...SHINY_HAIR_COLORS,
    ...GAKUEN_HAIR_COLORS,
    ...CINDERELLA_HAIR_COLORS
  });

  const seriesOrder = ["allstars", "million", "cinderella", "shiny", "gakuen"];
  const seriesLabels = {
      "allstars": "올스타즈",
      "million": "밀리언 스타즈",
      "cinderella": "신데렐라 걸즈",
      "shiny": "샤이니 컬러즈",
      "gakuen": "학원 아이돌마스터",
      "all": "전체"
  };

  const seriesIcons = {
      "allstars": "assets/icons/allstars.svg",
      "million": "assets/icons/millionstars.svg",
      "cinderella": "assets/icons/cinderella.svg",
      "shiny": "assets/icons/shinycolors.svg",
      "gakuen": "assets/icons/gakuen.svg"
  };

  const attributeLabels = {
      "illumination STARS": "일루미네이션 스타즈",
      "L’Antica": "안티카",
      "Houkago Climax Girls": "방과후 클라이맥스 걸즈",
      "ALSTROEMERIA": "알스트로메리아",
      "Straylight": "스트레이라이트",
      "noctchill": "녹칠",
      "SHHis": "시즈",
      "CoMETIK": "코메틱",
      "HATSUBOSHI GAKUEN": "하츠보시 학원",
      "Cute": "Cute",
      "Cool": "Cool",
      "Passion": "Passion"
  };

  const difficultyLabels = {
      "easy": "Easy",
      "normal": "Normal",
      "hard": "Hard",
      "very-hard": "Very Hard"
  };

  window.IdolmasterQuizData = Object.freeze({
    ALLSTARS_IDOLS,
    MILLION_IDOLS,
    SHINY_IDOLS,
    GAKUEN_IDOLS,
    CINDERELLA_IDOLS,
    SERIES_IDOLS,
    ALLSTARS_IMAGE_FILES,
    MILLION_IMAGE_FILES,
    SHINY_IMAGE_FILES,
    GAKUEN_IMAGE_FILES,
    CINDERELLA_IMAGE_FILES,
    SERIES_IMAGE_FILES,
    ALLSTARS_HAIR_COLORS,
    MILLION_HAIR_COLORS,
    SHINY_HAIR_COLORS,
    GAKUEN_HAIR_COLORS,
    CINDERELLA_HAIR_COLORS,
    SERIES_HAIR_COLORS,
    IDOLS,
    ADDITIONAL_IDOLS,
    ALL_IDOLS,
    IDOL_IMAGE_FILES,
    HAIR_COLORS,
    ADDITIONAL_HAIR_COLORS,
    seriesOrder,
    seriesLabels,
    seriesIcons,
    attributeLabels,
    difficultyLabels
  });
})();
