"use strict";

/*
  data.js
  ???/???/?? ??? ?? ?????.
  index.html?? script.js?? ?? ???? window.IdolmasterQuizData? ?????.
  ? ???? ??? ?? ADDITIONAL_IDOLS? ADDITIONAL_HAIR_COLORS? ?? no ?? ???? ???.
*/
(() => {
  const IDOLS = [
    { no: 1, attribute: "Princess", group: "765PRO ALLSTARS", jpName: "天海 春香", name: "아마미 하루카", hex: "#e22b30", image: "아마미 하루카.png" },
    { no: 2, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "エミリー スチュアート", name: "에밀리 스튜어트", hex: "#554171", image: "에밀리 스튜어트.png" },
    { no: 3, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "春日 未来", name: "카스가 미라이", hex: "#ea5b76", image: "카스가 미라이.png" },
    { no: 4, attribute: "Princess", group: "765PRO ALLSTARS", jpName: "我那覇 響", name: "가나하 히비키", hex: "#01adb9", image: "가나하 히비키.png" },
    { no: 5, attribute: "Princess", group: "765PRO ALLSTARS", jpName: "菊地 真", name: "키쿠치 마코토", hex: "#515558", image: "키쿠치 마코토.png" },
    { no: 6, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "高坂 海美", name: "코사카 우미", hex: "#e9739b", image: "코사카 우미.png" },
    { no: 7, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "佐竹 美奈子", name: "사타케 미나코", hex: "#58a6dc", image: "사타케 미나코.png" },
    { no: 8, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "高山 紗代子", name: "타카야마 사요코", hex: "#7f6575", image: "타카야마 사요코.png" },
    { no: 9, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "田中 琴葉", name: "타나카 코토하", hex: "#92cfbb", image: "타나카 코토하.png" },
    { no: 10, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "徳川 まつり", name: "토쿠가와 마츠리", hex: "#5abfb7", image: "토쿠가와 마츠리.png" },
    { no: 11, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "中谷 育", name: "나카타니 이쿠", hex: "#f7e78e", image: "나카타니 이쿠.png" },
    { no: 12, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "七尾 百合子", name: "나나오 유리코", hex: "#c7b83c", image: "나나오 유리코.png" },
    { no: 13, attribute: "Princess", group: "765PRO ALLSTARS", jpName: "萩原 雪歩", name: "하기와라 유키호", hex: "#d3dde9", image: "하기와라 유키호.png" },
    { no: 14, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "福田 のり子", name: "후쿠다 노리코", hex: "#eceb70", image: "후쿠다 노리코.png" },
    { no: 15, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "松田 亜利沙", name: "마츠다 아리사", hex: "#b54461", image: "마츠다 아리사.png" },
    { no: 16, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "矢吹 可奈", name: "야부키 카나", hex: "#f5ad3b", image: "야부키 카나.png" },
    { no: 17, attribute: "Princess", group: "MILLION LIVE! THEATER", jpName: "横山 奈緒", name: "요코야마 나오", hex: "#788bc5", image: "요코야마 나오.png" },
    { no: 18, attribute: "Fairy", group: "765PRO ALLSTARS", jpName: "秋月 律子", name: "아키즈키 리츠코", hex: "#01a860", image: "아키즈키 리츠코.png" },
    { no: 19, attribute: "Fairy", group: "765PRO ALLSTARS", jpName: "如月 千早", name: "키사라기 치하야", hex: "#2743d2", image: "키사라기 치하야.png" },
    { no: 20, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "北沢 志保", name: "키타자와 시호", hex: "#afa690", image: "키타자와 시호.png" },
    { no: 21, attribute: "Fairy", group: "765PRO ALLSTARS", jpName: "四条 貴音", name: "시죠 타카네", hex: "#a6126a", image: "시죠 타카네.png" },
    { no: 22, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "ジュリア", name: "줄리아", hex: "#d7385f", image: "줄리아.png" },
    { no: 23, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "白石 紬", name: "시라이시 츠무기", hex: "#ebe1ff", image: "시라이시 츠무기.png" },
    { no: 24, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "周防 桃子", name: "스오 모모코", hex: "#efb864", image: "스오 모모코.png" },
    { no: 25, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "天空橋 朋花", name: "텐쿠바시 토모카", hex: "#bee3e3", image: "텐쿠바시 토모카.png" },
    { no: 26, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "所 恵美", name: "토코로 메구미", hex: "#454341", image: "토코로 메구미.png" },
    { no: 27, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "永吉 昴", name: "나가요시 스바루", hex: "#aeb49c", image: "나가요시 스바루.png" },
    { no: 28, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "二階堂 千鶴", name: "니카이도 치즈루", hex: "#f19557", image: "니카이도 치즈루.png" },
    { no: 29, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "ロコ", name: "로코", hex: "#fff03c", image: "로코.png" },
    { no: 30, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "舞浜 歩", name: "마이하마 아유무", hex: "#e25a9b", image: "마이하마 아유무.png" },
    { no: 31, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "真壁 瑞希", name: "마카베 미즈키", hex: "#99b7dc", image: "마카베 미즈키.png" },
    { no: 32, attribute: "Fairy", group: "765PRO ALLSTARS", jpName: "水瀬 伊織", name: "미나세 이오리", hex: "#fd99e1", image: "미나세 이오리.png" },
    { no: 33, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "最上 静香", name: "모가미 시즈카", hex: "#6495cf", image: "모가미 시즈카.png" },
    { no: 34, attribute: "Fairy", group: "MILLION LIVE! THEATER", jpName: "百瀬 莉緒", name: "모모세 리오", hex: "#f19591", image: "모모세 리오.png" },
    { no: 35, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "伊吹 翼", name: "이부키 츠바사", hex: "#fed552", image: "이부키 츠바사.png" },
    { no: 36, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "大神 環", name: "오오가미 타마키", hex: "#ee762e", image: "오오가미 타마키.png" },
    { no: 37, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "北上 麗花", name: "키타카미 레이카", hex: "#6bb6b0", image: "키타카미 레이카.png" },
    { no: 38, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "木下 ひなた", name: "키노시타 히나타", hex: "#d1342c", image: "키노시타 히나타.png" },
    { no: 39, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "桜守 歌織", name: "사쿠라모리 카오리", hex: "#274079", image: "사쿠라모리 카오리.png" },
    { no: 40, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "篠宮 可憐", name: "시노미야 카렌", hex: "#b63b40", image: "시노미야 카렌.png" },
    { no: 41, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "島原 エレナ", name: "시마바라 엘레나", hex: "#9bce92", image: "시마바라 엘레나.png" },
    { no: 42, attribute: "Angel", group: "765PRO ALLSTARS", jpName: "高槻 やよい", name: "타카츠키 야요이", hex: "#f39939", image: "타카츠키 야요이.png" },
    { no: 43, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "豊川 風花", name: "토요카와 후카", hex: "#7278a8", image: "토요카와 후카.png" },
    { no: 44, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "野々原 茜", name: "노노하라 아카네", hex: "#eb613f", image: "노노하라 아카네.png" },
    { no: 45, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "箱崎 星梨花", name: "하코자키 세리카", hex: "#ed90ba", image: "하코자키 세리카.png" },
    { no: 46, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "馬場 このみ", name: "바바 코노미", hex: "#f1becb", image: "바바 코노미.png" },
    { no: 47, attribute: "Angel", group: "765PRO ALLSTARS", jpName: "双海 亜美", name: "후타미 아미", hex: "#ffe43f", image: "후타미 아미.png" },
    { no: 48, attribute: "Angel", group: "765PRO ALLSTARS", jpName: "双海 真美", name: "후타미 마미", hex: "#ffe43f", image: "후타미 마미.png" },
    { no: 49, attribute: "Angel", group: "765PRO ALLSTARS", jpName: "星井 美希", name: "호시이 미키", hex: "#b4e04b", image: "호시이 미키.png" },
    { no: 50, attribute: "Angel", group: "765PRO ALLSTARS", jpName: "三浦 あずさ", name: "미우라 아즈사", hex: "#9238be", image: "미우라 아즈사.png" },
    { no: 51, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "宮尾 美也", name: "미야오 미야", hex: "#d7a96b", image: "미야오 미야.png" },
    { no: 52, attribute: "Angel", group: "MILLION LIVE! THEATER", jpName: "望月 杏奈", name: "모치즈키 안나", hex: "#7e6ca8", image: "모치즈키 안나.png" }
  ];

  const ADDITIONAL_IDOLS = [
    { no: 1001, series: "shiny", attribute: "illumination STARS", group: "SHINY COLORS", jpName: "櫻木 真乃", name: "사쿠라기 마노", hex: "#ffbad6", image: "shiny/Mano_Sakuragi.png" },
    { no: 1002, series: "shiny", attribute: "illumination STARS", group: "SHINY COLORS", jpName: "風野 灯織", name: "카자노 히오리", hex: "#144384", image: "shiny/Hiori_Kazano.png" },
    { no: 1003, series: "shiny", attribute: "illumination STARS", group: "SHINY COLORS", jpName: "八宮 めぐる", name: "하치미야 메구루", hex: "#ffe012", image: "shiny/Meguru_Hachimiya.png" },
    { no: 1004, series: "shiny", attribute: "L’Antica", group: "SHINY COLORS", jpName: "月岡 恋鐘", name: "츠키오카 코가네", hex: "#f84cad", image: "shiny/Kogane_Tsukioka.png" },
    { no: 1005, series: "shiny", attribute: "L’Antica", group: "SHINY COLORS", jpName: "田中 摩美々", name: "타나카 마미미", hex: "#a846fb", image: "shiny/Mamimi_Tanaka.png" },
    { no: 1006, series: "shiny", attribute: "L’Antica", group: "SHINY COLORS", jpName: "白瀬 咲耶", name: "시라세 사쿠야", hex: "#006047", image: "shiny/Sakuya_Shirase.png" },
    { no: 1007, series: "shiny", attribute: "L’Antica", group: "SHINY COLORS", jpName: "三峰 結華", name: "미츠미네 유이카", hex: "#3b91c4", image: "shiny/Yuika_Mitsumine.png" },
    { no: 1008, series: "shiny", attribute: "L’Antica", group: "SHINY COLORS", jpName: "幽谷 霧子", name: "유코쿠 키리코", hex: "#d9f2ff", image: "shiny/Kiriko_Yukoku.png" },
    { no: 1009, series: "shiny", attribute: "Houkago Climax Girls", group: "SHINY COLORS", jpName: "小宮 果穂", name: "코미야 카호", hex: "#e5461c", image: "shiny/Kaho_Komiya.png" },
    { no: 1010, series: "shiny", attribute: "Houkago Climax Girls", group: "SHINY COLORS", jpName: "園田 智代子", name: "소노다 치요코", hex: "#f93b90", image: "shiny/Chiyoko_Sonoda.png" },
    { no: 1011, series: "shiny", attribute: "Houkago Climax Girls", group: "SHINY COLORS", jpName: "西城 樹里", name: "사이죠 쥬리", hex: "#ffc602", image: "shiny/Juri_Saijo.png" },
    { no: 1012, series: "shiny", attribute: "Houkago Climax Girls", group: "SHINY COLORS", jpName: "杜野 凛世", name: "모리노 린제", hex: "#89c3eb", image: "shiny/Rinze_Morino.png" },
    { no: 1013, series: "shiny", attribute: "Houkago Climax Girls", group: "SHINY COLORS", jpName: "有栖川 夏葉", name: "아리스가와 나츠하", hex: "#90e667", image: "shiny/Natsuha_Arisugawa.png" },
    { no: 1014, series: "shiny", attribute: "ALSTROEMERIA", group: "SHINY COLORS", jpName: "大崎 甘奈", name: "오사키 아마나", hex: "#f54275", image: "shiny/Amana_Osaki.png" },
    { no: 1015, series: "shiny", attribute: "ALSTROEMERIA", group: "SHINY COLORS", jpName: "大崎 甜花", name: "오사키 텐카", hex: "#e75bec", image: "shiny/Tenka_Osaki.png" },
    { no: 1016, series: "shiny", attribute: "ALSTROEMERIA", group: "SHINY COLORS", jpName: "桑山 千雪", name: "쿠와야마 치유키", hex: "#fafafa", image: "shiny/Chiyuki_Kuwayama.png" },
    { no: 1017, series: "shiny", attribute: "Straylight", group: "SHINY COLORS", jpName: "芹沢 あさひ", name: "세리자와 아사히", hex: "#f30100", image: "shiny/Asahi_Serizawa.png" },
    { no: 1018, series: "shiny", attribute: "Straylight", group: "SHINY COLORS", jpName: "黛 冬優子", name: "마유즈미 후유코", hex: "#5aff19", image: "shiny/Fuyuko_Mayuzumi.png" },
    { no: 1019, series: "shiny", attribute: "Straylight", group: "SHINY COLORS", jpName: "和泉 愛依", name: "이즈미 메이", hex: "#ff00ff", image: "shiny/Mei_Izumi.png" },
    { no: 1020, series: "shiny", attribute: "noctchill", group: "SHINY COLORS", jpName: "浅倉 透", name: "아사쿠라 토오루", hex: "#50d0d0", image: "shiny/Toru_Asakura.png" },
    { no: 1021, series: "shiny", attribute: "noctchill", group: "SHINY COLORS", jpName: "樋口 円香", name: "히구치 마도카", hex: "#be1e3e", image: "shiny/Madoka_Higuchi.png" },
    { no: 1022, series: "shiny", attribute: "noctchill", group: "SHINY COLORS", jpName: "福丸 小糸", name: "후쿠마루 코이토", hex: "#7967c3", image: "shiny/Koito_Fukumaru.png" },
    { no: 1023, series: "shiny", attribute: "noctchill", group: "SHINY COLORS", jpName: "市川 雛菜", name: "이치카와 히나나", hex: "#ffc639", image: "shiny/Hinana_Ichikawa.png" },
    { no: 1024, series: "shiny", attribute: "SHHis", group: "SHINY COLORS", jpName: "七草 にちか", name: "나나쿠사 니치카", hex: "#a6cdb6", image: "shiny/Nichika_Nanakusa.png" },
    { no: 1025, series: "shiny", attribute: "SHHis", group: "SHINY COLORS", jpName: "緋田 美琴", name: "아케타 미코토", hex: "#760f10", image: "shiny/Mikoto_Aketa.png" },
    { no: 1026, series: "shiny", attribute: "CoMETIK", group: "SHINY COLORS", jpName: "斑鳩 ルカ", name: "이카루가 루카", hex: "#35281f", image: "shiny/Luca_Ikaruga.png" },
    { no: 1027, series: "shiny", attribute: "CoMETIK", group: "SHINY COLORS", jpName: "鈴木 羽那", name: "스즈키 하나", hex: "#e0b5d3", image: "shiny/Hana_Suzuki.png" },
    { no: 1028, series: "shiny", attribute: "CoMETIK", group: "SHINY COLORS", jpName: "郁田 はるき", name: "이쿠타 하루키", hex: "#ead7a4", image: "shiny/Haruki_Ikuta.png" },
    { no: 2001, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "花海 咲季", name: "하나미 사키", hex: "#e30f25", image: "gakuen/Saki_Hanami.png" },
    { no: 2002, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "月村 手毬", name: "츠키무라 테마리", hex: "#0c7bbb", image: "gakuen/Temari_Tsukimura.png" },
    { no: 2003, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "藤田 ことね", name: "후지타 코토네", hex: "#f8c112", image: "gakuen/Kotone_Fujita.png" },
    { no: 2004, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "有村 麻央", name: "아리무라 마오", hex: "#7f1184", image: "gakuen/Mao_Arimura.png" },
    { no: 2005, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "葛城 リーリヤ", name: "카츠라기 리리야", hex: "#eafdff", image: "gakuen/Lilja_Katsuragi.png" },
    { no: 2006, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "倉本 千奈", name: "쿠라모토 치나", hex: "#f68b1f", image: "gakuen/China_Kuramoto.png" },
    { no: 2007, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "紫雲 清夏", name: "시운 스미카", hex: "#7cfc00", image: "gakuen/Sumika_Shiun.png" },
    { no: 2008, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "篠澤 広", name: "시노사와 히로", hex: "#00afcc", image: "gakuen/Hiro_Shinosawa.png" },
    { no: 2009, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "姫崎 莉波", name: "히메사키 리나미", hex: "#f6adc6", image: "gakuen/Rinami_Himesaki.png" },
    { no: 2010, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "花海 佑芽", name: "하나미 우메", hex: "#ea533a", image: "gakuen/Ume_Hanami.png" },
    { no: 2011, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "秦谷 美鈴", name: "하타야 미스즈", hex: "#7a99cf", image: "gakuen/Misuzu_Hataya.png" },
    { no: 2012, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "十王 星南", name: "주오 세나", hex: "#f6ae54", image: "gakuen/Sena_Juo.png" },
    { no: 2013, series: "gakuen", attribute: "HATSUBOSHI GAKUEN", group: "GAKUEN IDOLM@STER", jpName: "雨夜 燕", name: "아마야 츠바메", hex: "#7b68ee", image: "gakuen/Tsubame_Amaya.png" }
  ];

  const ALL_IDOLS = [...IDOLS, ...ADDITIONAL_IDOLS];

  const IDOL_IMAGE_FILES = {
    1: "Haruka_Amami.png",
    2: "Emily_Stewart.png",
    3: "Mirai_Kasuga.png",
    4: "Hibiki_Ganaha.png",
    5: "Makoto_Kikuchi.png",
    6: "Umi_Kousaka.png",
    7: "Minako_Satake.png",
    8: "Sayoko_Takayama.png",
    9: "Kotoha_Tanaka.png",
    10: "Matsuri_Tokugawa.png",
    11: "Iku_Nakatani.png",
    12: "Yuriko_Nanao.png",
    13: "Yukiho_Hagiwara.png",
    14: "Noriko_Fukuda.png",
    15: "Arisa_Matsuda.png",
    16: "Kana_Yabuki.png",
    17: "Nao_Yokoyama.png",
    18: "Ritsuko_Akizuki.png",
    19: "Chihaya_Kisaragi.png",
    20: "Shiho_Kitazawa.png",
    21: "Takane_Shijou.png",
    22: "Julia.png",
    23: "Tsumugi_Shirokane.png",
    24: "Momoko_Suou.png",
    25: "Tomoka_Tenkubashi.png",
    26: "Megumi_Tokoro.png",
    27: "Subaru_Nagayoshi.png",
    28: "Chizuru_Nikaido.png",
    29: "Roco.png",
    30: "Ayumu_Maihama.png",
    31: "Mizuki_Makabe.png",
    32: "Iori_Minase.png",
    33: "Shizuka_Mogami.png",
    34: "Rio_Momose.png",
    35: "Tsubasa_Ibuki.png",
    36: "Tamaki_Ogami.png",
    37: "Reika_Kitakami.png",
    38: "Hinata_Kinoshita.png",
    39: "Kaori_Sakuramori.png",
    40: "Karen_Shinomiya.png",
    41: "Elena_Shimabara.png",
    42: "Yayoi_Takatsuki.png",
    43: "Fuka_Toyokawa.png",
    44: "Akane_Nonohara.png",
    45: "Serika_Hakozaki.png",
    46: "Konomi_Baba.png",
    47: "Ami_Futami.png",
    48: "Mami_Futami.png",
    49: "Miki_Hoshii.png",
    50: "Azusa_Miura.png",
    51: "Miya_Miake.png",
    52: "Anna_Mochizuki.png"
  };

  const HAIR_COLORS = {
    1: "#8e5049",
    2: "#e2c95d",
    3: "#754842",
    4: "#242633",
    5: "#3d3c46",
    6: "#9a6a35",
    7: "#674d3f",
    8: "#8c8179",
    9: "#a04c41",
    10: "#72b0b0",
    11: "#4c352f",
    12: "#4973a2",
    13: "#c8925e",
    14: "#e2be4f",
    15: "#4c2626",
    16: "#cf843d",
    17: "#845743",
    18: "#8a6043",
    19: "#28355a",
    20: "#826a5c",
    21: "#d9d8e6",
    22: "#b1382f",
    23: "#d6e7fa",
    24: "#9b764b",
    25: "#d4ae76",
    26: "#9a6d3d",
    27: "#868159",
    28: "#5b3c24",
    29: "#c9c0b8",
    30: "#ea60ab",
    31: "#dbc2e5",
    32: "#9a6643",
    33: "#283257",
    34: "#e7bb5d",
    35: "#d1a649",
    36: "#d96b45",
    37: "#334a5a",
    38: "#683f32",
    39: "#95887c",
    40: "#d8b863",
    41: "#cbdaa2",
    42: "#d88445",
    43: "#576496",
    44: "#e46a47",
    45: "#b58a61",
    46: "#a26c3f",
    47: "#a17542",
    48: "#a17542",
    49: "#f2e48e",
    50: "#303a6c",
    51: "#b9915a",
    52: "#675e8f"
  };

  const ADDITIONAL_HAIR_COLORS = {
    1001: "#c99f8e",
    1002: "#31363c",
    1003: "#f8e699",
    1004: "#967b7b",
    1005: "#4a3458",
    1006: "#433846",
    1007: "#3b3344",
    1008: "#b7aab0",
    1009: "#ca797e",
    1010: "#866662",
    1011: "#f8dc9d",
    1012: "#535977",
    1013: "#ef9b8a",
    1014: "#9a5a5c",
    1015: "#a76868",
    1016: "#7c684e",
    1017: "#e1d0c7",
    1018: "#4d4d5c",
    1019: "#89502e",
    1020: "#a1869d",
    1021: "#98353e",
    1022: "#4d4a66",
    1023: "#d0af9a",
    1024: "#919172",
    1025: "#985143",
    1026: "#403939",
    1027: "#b3b9ec",
    1028: "#e2bbb7",
    2001: "#cf7e7e",
    2002: "#5f6e73",
    2003: "#e7c95e",
    2004: "#d5a9b1",
    2005: "#e6dbdb",
    2006: "#887b70",
    2007: "#e7a25b",
    2008: "#ebdfcc",
    2009: "#d3a495",
    2010: "#b47a63",
    2011: "#5e577d",
    2012: "#fff1dc",
    2013: "#83818d"
  };

  const seriesOrder = ["allstars", "million", "shiny", "gakuen"];
  const seriesLabels = {
    allstars: "올스타즈",
    million: "밀리언 스타즈",
    shiny: "샤이니 컬러즈",
    gakuen: "학원 아이돌마스터",
    all: "전체"
  };

  const seriesIcons = {
    allstars: "assets/icons/allstars.svg",
    million: "assets/icons/millionstars.svg",
    shiny: "assets/icons/shinycolors.svg",
    gakuen: "assets/icons/gakuen.svg"
  };

  const attributeLabels = {
    "illumination STARS": "일루미네이션 스타즈",
    "L’Antica": "안티카",
    "Houkago Climax Girls": "방과후 클라이맥스 걸즈",
    "ALSTROEMERIA": "알스트로메리아",
    "Straylight": "스트레이라이트",
    "noctchill": "녹칠",
    "SHHis": "시즈",
    "CoMETIK": "코메틱",
    "HATSUBOSHI GAKUEN": "하츠보시 학원"
  };

  const difficultyLabels = {
    easy: "Easy",
    normal: "Normal",
    hard: "Hard"
  };

  window.IdolmasterQuizData = Object.freeze({
    IDOLS,
    ADDITIONAL_IDOLS,
    ALL_IDOLS,
    IDOL_IMAGE_FILES,
    HAIR_COLORS,
    ADDITIONAL_HAIR_COLORS,
    seriesOrder,
    seriesLabels,
    seriesIcons,
    attributeLabels,
    difficultyLabels
  });
})();
